### ISSUE TITLE
Bars API is broken/incomplete

### ISSUE THREAD

**Issue by pps83** [alpacahq/user-docs#130]
https://alpaca.market/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/historical/#bars

The API isn't complete. It must return also number of trades and volume weighted  (average price). How did you even come up with such incomplete spec for bars. WTF?!

Check polygon, check IEX, why the hell your API is missing that data. Did you decide that it wasn't useful just like that?

**Comment by gnvk** [comment]
Thank you for reporting this issue. The bars endpoint now does return the number of trades (`n`) and the volume weighted average price (`vw`).

**Comment by pps83** [comment]
@gnvk This doesn't seem to be correct. This is the docs for bars api:

![image](https://user-images.githubusercontent.com/1614246/158906062-65482693-6f66-471e-a089-ba14c49d4f88.png)

The other issue: I've never seen SUCH ABSOLUTELY BROKEN USELESS docs for the API. 
I absolutely DO NOT understand HOW to make a single request. What a failure.

HOW DO I MAKE A SINGLE REQUEST for historical data?!
What the hell, who wrote these useless docs? I absolutely cannot find where/how to place my private key, and how to even find it. Completely failure. I strongly suggest to take a look at polygon and how their APIs are well done.
