### ISSUE TITLE
Define possible values of asset_class

### ISSUE THREAD

**Issue by mtcliatt** [alpacahq/user-docs#23]
The [Get Assets](https://docs.alpaca.markets/api-documentation/web-api/assets/#get-assets) API endpoint has an `asset_class` parameter with a default value of `"us_equity"`.
What values would be accepted by this endpoint?

**Comment by umitanuki** [comment]
It is currently only `us_equity`. Other values are reserved for future extension.

**Comment by mtcliatt** [comment]
This issue was for that to be added to the docs?

**Comment by umitanuki** [comment]
Sounds good. It wasn't clear if this was one time question or suggestion to make change to the doc. We can add the explanation to the doc.
