### ISSUE TITLE
Typo in Streaming docs

### ISSUE THREAD

**Issue by mtcliatt** [alpacahq/user-docs#34]
Find phrase "updates **in in** addition" on page https://docs.alpaca.markets/api-documentation/web-api/streaming/

**Comment by umitanuki** [comment]
Could you propose PR here? https://github.com/alpacahq/user-docs/edit/master/content/api-documentation/web-api/streaming/_index.md

**Comment by mtcliatt** [comment]
What would the PR fix? This issue has been closed ;)

**Comment by umitanuki** [comment]
Sorry for confusion. I was saying you can open a PR as this is a public repo that is designed to accept contributions from you :) I will fix it anyway now.

**Comment by umitanuki** [comment]
Actually, the language doesn't seem wrong to me. 

```
Similarly, if you want to add more streams to get updates in in addition to the ones you are already doing so, you must send all the stream names not only the new ones.
```
If it's better to put a punctuation between two `in`s, I'm happy to.

**Comment by umitanuki** [comment]
Seems like someone just fixed it accordingly anyway.
